services:
  - type: web
    name: lipu143
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: your-telegram-bot-token
      - key: MONGO_URI
        value: your-mongodb-uri
      - key: SHORTNER_API
        value: your-shortener-api-key
      - key: FLASK_URL
        value: https://your-app-name.onrender.com
      - key: LIKE_API_URL
        value: https://example.com/likeapi?uid={uid}
      - key: HOW_TO_VERIFY_URL
        value: https://your-help-url
      - key: VIP_ACCESS_URL
        value: https://your-vip-url
      - key: ADMIN_IDS
        value: 123456789,987654321